services:
  - type: web
    name: vital-ativa-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install && npm start
    startCommand: node src/server.js
    autoDeploy: true