services:
  - type: web
    name: vital-ativa-backend
    env: node
    region: oregon
    buildCommand: cd backend && npm install
    startCommand: cd backend && node src/server.js
    autoDeploy: true